databases:
  - name: meal_master-db
    databaseName: meal_master
    user: meal_master
    plan: free

services:
  - type: web
    name: meal_master
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meal_master-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
